config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}

  root 'static_pages#home'
  get 'static_pages/about'

  get '/assign', to: 'tasks#assign_task'
  get '/complete', to: 'tasks#complete_task'

  resources :tasks
  resources :users

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "task.JPG"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  def set_task(user)
    self.update(assigned_user_id: user.id)
  end

  def mark_task
    self.update(complete: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :original => Proc.new { |instance| instance.resize },
     # :large => "800x800#",
     :medium => "240x240#",
     # :small => "100x100#",
     :thumb => "32x32#"
     },
         default_url: 'april2.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_many :tasks


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def profile
    @user = current_user
    @requested_tasks = @user.tasks
    @claimed_tasks = Task.where(assigned_user_id: current_user.id)
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def assign_task
    @task = Task.find(params[:task_id])
    @task.set_task(current_user)
    redirect_to tasks_path
  end

  def complete_task
    @task = Task.find(params[:task_id])
    @task.mark_task
    redirect_to user_path(current_user)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private
    def find_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :location, :description, :assigned_user_id, :tokens, :image, :user_id, :category, :complete)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @requested_tasks = @user.tasks
    @claimed_tasks = Task.where(assigned_user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class = "transparent z-depth-0">
    <div class="">
      <a href="/" class="brand-logo"><%= image_tag "taskbunny.png" %></a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Tasks', tasks_path %></li>
        <% if current_user %>
        <li><%= link_to 'New Task', new_task_path %></li>
        <li><%= link_to 'Profile', user_path(current_user) %></li>
        <li><%= link_to 'Log Out',destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Tasks', tasks_path %></li>
        <% if current_user %>
        <li><%= link_to 'New Task', new_task_path %></li>
        <li><%= link_to 'Profile', user_path(current_user) %></li>
        <li><%= link_to 'Log Out',destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskBunny</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="blue lighten-2">
<%= render 'layouts/navbar' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/static_pages/about.html.haml
%h1 StaticPages#about
%p Find me in app/views/static_pages/about.html.haml

app/views/static_pages/home.html.erb
<div class="parallax-container">
	<div class="parallax"><img src= "http://dailybunny.org/wp-content/uploads/2013/01/7ficN.gif"></div>
</div>

<div class="section white">
		<h2 class="header"><h1>How <strong>TaskBunny</strong> works</h1></h2>
    <div class="grey-text text-darken-3 lighten-3 left-align">
    <!-- <ul> -->
      <li>TaskBunny is the smart way to get things done by connecting you with others in your neighborhood.</li>
      <li>We find the best people to help you. </li>
      <li>You can trust our team of smart, talented Taskers, who have all been thoroughly vetted.</li>
      <li>You outsource errands you don't want to do.</li>
      <li>Just tell us what you need done and we connect you to qualified Taskers available to help.</li>
    <!-- </ul> -->
    </div>
  <div class="row container">
	</div>
	<div class="row container col s2 m4">
		<div class="parallax col s2 m4 responsive-img hide-on-med-and-down"><img src=<%= image_path "ryan.png" %>></div>
    <!-- <img class="parallax col s2 m4 responsive-img" src="images/ryan.png"> -->
	</div>
</div>

app/views/tasks/_form.html.haml
.section.white
  .container
    = form_for @task, html: {multipart: true} do |f|
      = f.label :name
      = f.text_field :name

      = f.label :description
      = f.text_area :description

      = f.label :location
      = f.text_field :location

      = f.label :tokens
      = f.text_field :tokens

      = f.label :category
      = f.select :category, options_for_select(['Help Moving', 'Handyman', 'Cleaning', 'Shopping + Delivery', 'Parties + Events'])

      %br

      = f.file_field :image

      = f.hidden_field :user_id, {value: current_user.id}

      = f.submit class: 'btn'

app/views/tasks/edit.html.haml
%h1 Edit Task

= render 'tasks/form'

app/views/tasks/index.html.haml
%h1.center All Tasks
- @tasks.each do |x|
  .row
    .card.green.darken-1.col.s12.m5
      .card-image.waves-effect.waves-block.waves-light
        = image_tag x.image.url(:medium)
      .card-content.white-text
        %span.card-title.activator.grey-text.text-darken-4
          = x.name.titleize
          %br
          %i.material-icons.right more_vert
        - if x.user_id != current_user.id
          - if x.complete != true
            %a
              = link_to 'Claim Task', assign_path(:task_id => x.id), class: 'btn white-text'
          - else
            %a.white-text
              = link_to 'Completed', tasks_path, class: 'btn white-text disabled'
          %a
            = link_to "#{x.user.first_name}'s Profile", user_path(x.user.id), class: 'btn right-align white-text'
        - else
          %a
            = link_to 'Edit Task', edit_task_path(x), class: 'btn right-align white-text'
      .card-reveal
        %span.card-title.grey-text.text-darken-4
          = x.name.titleize
        %i.material-icons.right close
        %p
          Description: #{x.description}
        %p
          Where: #{x.location}
        %p
          Event Created: #{x.created_at.strftime("%m/%d/%Y")}
        %p
          Posted By: #{x.user.email}
        %p
          Tokens: #{x.tokens}
        %p
          Category: #{x.category}
          

app/views/tasks/new.html.haml
%h1 New Task
= render 'tasks/form'

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

app/views/users/show.html.haml
- if @user.id == current_user.id
  %h1
    = "Welcome, #{current_user.first_name}"
  %br
.right-align
  = image_tag @user.avatar.url(style: :thumb)
  %h4
    = @user.first_name
    %br
    = @user.last_name
    %br
    = @user.email
    %br
    Tokens: 125

%h1 Requested Tasks
- @requested_tasks.each do |x|
  .row
    .card.green.darken-1.col.s12.m5
      .card-content.white-text
        %h4.card-title.center-align= x.name.titleize
        %p
          Description: #{x.description}
        %p
          Where: #{x.location}
        %p
          Event Created: #{x.created_at.strftime("%m/%d/%Y")}
        %p
          Posted By: #{x.user.email}
        %p
          Tokens: #{x.tokens}
        %p
          Category: #{x.category}
        .card-action.center
          - if x.user_id != current_user.id
            - if x.complete != true
              %a
                = link_to 'Claim Task', assign_path(:task_id => x.id), class: 'btn white-text'
            - else
              %a.white-text
                = link_to 'Completed', class: 'white-text'
            %a
              = link_to "#{x.user.first_name}'s Profile", user_path(x.user.id), class: 'btn right-align white-text'
          - else
            %a
              = link_to 'Edit Task', edit_task_path(x), class: 'btn right-align white-text'


%h1 Claimed Tasks
- @claimed_tasks.each do |x|
  .row
    .card.green.darken-1.col.s12.m5
      .card-content.white-text
        %h4.card-title.center-align= x.name.titleize
        %p
          Description: #{x.description}
        %p
          Where: #{x.location}
        %p
          Event Created: #{x.created_at.strftime("%m/%d/%Y")}
        %p
          Posted By: #{x.user.email}
        %p
          Tokens: #{x.tokens}
        %p
          Category: #{x.category}
        .card-action.center
          - if x.assigned_user_id == current_user.id
            - if x.complete != true
              %a
                = link_to 'Mark as Complete', complete_path(:task_id => x.id), class: 'btn white-text'
            - else
              %a
                = link_to 'Completed', complete_path(:task_id => x.id), class: 'btn white-text disabled'
            %a
              = link_to "#{x.user.first_name}'s Profile", user_path(x.user.id), class: 'btn right-align white-text'
          - else
            %a
              = link_to 'Edit Task', edit_task_path(x), class: 'btn right-align white-text'
          